---

- name: Install backupninja packages
  apt:
    state: present
    pkg:
      - dialog
      - backupninja
      - duplicity
      - python3-paramiko
  when: ansible_os_family == "Debian"

- name: Install backupninja packages
  yum:
    state: present
    pkg:
      - dialog
      - backupninja
      - duplicity
      - python3-paramiko
  when: ansible_os_family == "RedHat"

- name: Create reports directory
  file: state=directory path="{{item}}" owner=root group={{backupninja_admingroup}} mode=0700
  with_items:
    - "{{backupninja_configdir}}"
    - "{{backupninja_reportdir}}"
  tags:
    - backupninja

- name: Copy additional backupninja plugins
  copy: src="{{item}}" dest="/usr/share/backupninja/{{item}}" owner=root group=root mode=0644
  with_items:
    - mongodb
    - mongodb.helper
  when:
    - backupninja_support_mongodb|bool
    - enable_backups|bool

- name: Template backup.d files
  template: src="{{item}}.j2" dest="/etc/backup.d/{{item}}" owner=root group=root mode=0600
  with_items:
    - "{{backup_templates|default([])}}"
    - "{{backupninja_default_jobs|default([])}}"
  when:
    - enable_backups|bool
  tags:
    - backupninja
    - backuptasks

- name: Template backupninja.conf
  template: src="backupninja.conf.j2" dest="/etc/backupninja.conf" owner=root group=root mode=0600
  tags:
    - backupninja
    - backupninja.conf
